# command line: run_hcn.py -c config/HCN_CV.yaml --use_gpu -w work_dir/HCN_CV

config: config/HCN_CV.yaml
debug: false
device: 0
eval_interval: 5
feeder: feeder.feeder_hcn.FeederHCN
ignore_weights: []
log_interval: 100
loss: torch.nn.CrossEntropyLoss
model: model.hcn.Model
model_args:
    in_channels: 3
    num_class: 60
num_epoch: 200
num_worker: 4
optimizer: torch.optim.Adam
optimizer_args:
    lr: 0.001
    weight_decay: 0.0001
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
scheduler: torch.optim.lr_scheduler.ExponentialLR
scheduler_args:
    gamma: 0.99
show_topk:
- 1
- 2
- 5
start_epoch: 0
test_batch_size: 64
test_feeder_args:
    action_classes: 60
    data_path: ./data/NTU-RGB-D/xview/val_data.npy
    label_path: ./data/NTU-RGB-D/xview/val_label.pkl
    meta_path: ./data/NTU-RGB-D/xview/val_num_frame.npy
train_batch_size: 64
train_feeder_args:
    action_classes: 60
    data_path: ./data/NTU-RGB-D/xview/train_data.npy
    label_path: ./data/NTU-RGB-D/xview/train_label.pkl
    meta_path: ./data/NTU-RGB-D/xview/train_num_frame.npy
use_gpu: true
weights: null
work_dir: work_dir/HCN_CV
