# Configuration for HCN (Cross-subject on NTURGB+D) - https://arxiv.org/abs/1804.06055
work_dir: ./work_dir/HCN_CS

num_epoch: 200
# feeder
feeder: feeder.feeder_hcn.FeederHCN
train_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/train_data.npy
  label_path: ./data/NTU-RGB-D/xsub/train_label.pkl
  meta_path: ./data/NTU-RGB-D/xsub/train_num_frame.npy
  action_classes: 60
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xsub/val_data.npy
  label_path: ./data/NTU-RGB-D/xsub/val_label.pkl
  meta_path: ./data/NTU-RGB-D/xsub/val_num_frame.npy
  action_classes: 60
train_batch_size: 64
test_batch_size: 64

# model
model: model.hcn.Model
model_args:
  in_channels: 3
  num_class: 60
loss: torch.nn.CrossEntropyLoss

# optim
optimizer: torch.optim.Adam
optimizer_args:
  lr: 0.001
  weight_decay: 0.0001

# scheduler
scheduler: torch.optim.lr_scheduler.ExponentialLR
scheduler_args:
  gamma: 0.99